name: code_scan_listener
description: Listen for any hardware barcode(or qrcode) scanner without any manufacturer SDK
version: 0.4.1
homepage: https://github.com/utamori/code_scan_listener
topics: [barcode, qrcode, scanner, listener, hardware-key-board]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
